//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportHub_CSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.REVIEWs = new HashSet<REVIEW>();
        }
    
        public int BookingID { get; set; }
        public int MemberID { get; set; }
        public int FacilityID { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string TimeSlot { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual FACILITY FACILITY { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
    }
}
