//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//------------------------------------------------------------------------------

namespace SportHub_CSharp.Models
{
    using System;
    using System.Collections.Generic;

    public partial class EQUIPMENT
    {
        public EQUIPMENT()
        {
            this.RENTALs = new HashSet<RENTAL>();
        }

        public int EquipmentID { get; set; }

        public string Name { get; set; }

        public string Type { get; set; }

        public int QuantityAvailable { get; set; }

        public Nullable<decimal> RentalFee { get; set; }

        public virtual ICollection<RENTAL> RENTALs { get; set; }
    }
}