//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportHub_CSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INQUIRY
    {
        public int InquiryID { get; set; }
        public string GuestName { get; set; }
        public string GuestEmail { get; set; }
        public string Message { get; set; }
        public System.DateTime SentDate { get; set; }
    }
}
