//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your
//     application.
//     Manual changes to this file will be overwritten if the code is
//     regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportHub_CSharp.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RENTAL
    {
        public int RentalID { get; set; }

        public int MemberID { get; set; }

        public int EquipmentID { get; set; }

        public System.DateTime RentDate { get; set; }

        public Nullable<System.DateTime> ReturnDate { get; set; }

        public string Status { get; set; }

        public virtual EQUIPMENT EQUIPMENT { get; set; }

        public virtual MEMBER MEMBER { get; set; }
    }
}