//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportHub_CSharp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMPLE_REVIEW
    {
        public int ReviewID { get; set; }
        public string ReviewerName { get; set; }
        public int Rating { get; set; }
        public string ReviewComment { get; set; }
        public System.DateTime ReviewDate { get; set; }
    }
}
